#!/usr/bin/env bash
# Installs and configures Nginx in web server Nginx

sudo apt update

sudo apt install -y nginx

echo 'server {
    listen 80;
    server_name _;

    location / {
        return 200 "Hello World!\n";
    }
}' | sudo tee /etc/nginx/sites-available/hello-world > /dev/null

sudo ln -s /etc/nginx/sites-available/hello-world /etc/nginx/sites-enabled/

#removing the default
sudo rm /etc/nginx/sites-enabled/default

#test NGINX
sudo nginx -t

#restarting NGINX
sudo /etc/init.d/nginx restart

